import type { InitializrStrings } from "./initializr.types"

export const initializrCopy = {
  en: {
    heroKicker: "StackForge Initializr",
    heroTitle: "Generate and download an API scaffold",
    heroSubtitle: "Choose a stack, pick a theme, and export a ZIP in one click.",
    reset: "Reset Defaults",
    theme: "Theme",
    locale: "Language",
    projectName: "Project Name",
    profile: "Profile",
    language: "Code Language",
    database: "Database",
    architecture: "Architecture",
    apiStyle: "API Style",
    packageManager: "Package Manager",
    featureSet: "Feature Set",
    installSteps: "Show install and run steps after generation",
    executeGenerator: "Execute Generator",
    generateTitle: "Generate and Download ZIP",
    generateDescription: "The backend scaffolds the project and returns a compact .zip to your browser.",
    projectWillBeCreated: "One click download for",
    projectAdjusted: "Project name adjusted to",
    projectRules: "only a-z, 0-9, - and _ are allowed",
    apiBaseUrl: "API base URL",
    usingProxy: "using Vite /api proxy",
    generateButton: "Generate and Download",
    generatingButton: "Generating ZIP...",
    downloadStatus: "Download Status",
    downloadDescription: "Result of the compacted project generation.",
    noDownload: "No download yet. Click Generate and Download to get your .zip file.",
    generateDownloadFailed: "Failed to generate and download the project.",
    invalidDownloadResponse: "Failed to read download token. Invalid server response.",
    downloadFileFailed: "Failed to download the generated file.",
    unexpectedDownloadError: "Unexpected zip download failure.",
    cleanupDownloads: "Clean Downloads",
    cleaningDownloads: "Cleaning downloads...",
    cleanupDownloadsFailed: "Failed to clean downloads.",
    cleanupDownloadsSuccess: "Downloads cleaned successfully.",
    nextSteps: "Next Steps",
    equivalentCli: "Equivalent CLI",
    referenceOnly: "Reference only. Generation now happens directly via button.",
    downloadStarted: "Download initiated",
    installLine: "install",
    runLine: "run dev",
    commandPrefix: "pnpm dev:new-project --",
    themes: {
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    locales: {
      en: "English",
      pt: "Português",
      es: "Español",
    },
    choices: {
      profile: {
        lite: "Lite",
        full: "Full",
      },
      language: {
        javascript: "JavaScript",
        typescript: "TypeScript",
      },
      database: {
        json: "JSON",
        postgresql: "PostgreSQL",
        mysql: "MySQL",
        sqlite: "SQLite",
        sqlserver: "SQL Server",
      },
      architecture: {
        layered: "Layered",
        mvc: "MVC",
        clean: "Clean",
      },
      apiStyle: {
        rest: "REST",
        graphql: "GraphQL",
        hybrid: "Hybrid",
      },
      packageManager: {
        pnpm: "pnpm",
        npm: "npm",
        yarn: "yarn",
        bun: "bun",
      },
      featureSet: {
        auth: "Auth",
        email: "Email",
        both: "Both",
        none: "None",
      },
    },
  },
  pt: {
    heroKicker: "StackForge Initializr",
    heroTitle: "Gere e baixe um scaffold de API",
    heroSubtitle: "Escolha a stack, o tema e exporte um ZIP em um clique.",
    reset: "Restaurar padrão",
    theme: "Tema",
    locale: "Idioma",
    projectName: "Nome do projeto",
    profile: "Perfil",
    language: "Linguagem",
    database: "Banco de dados",
    architecture: "Arquitetura",
    apiStyle: "Estilo da API",
    packageManager: "Gerenciador de pacotes",
    featureSet: "Conjunto de features",
    installSteps: "Mostrar passos de instalação e execução após gerar",
    executeGenerator: "Executar gerador",
    generateTitle: "Gerar e baixar ZIP",
    generateDescription: "O backend cria o projeto e devolve um .zip compacto para o navegador.",
    projectWillBeCreated: "Download com um clique para",
    projectAdjusted: "Nome do projeto ajustado para",
    projectRules: "apenas a-z, 0-9, - e _ são permitidos",
    apiBaseUrl: "URL base da API",
    usingProxy: "usando proxy /api do Vite",
    generateButton: "Gerar e baixar",
    generatingButton: "Gerando ZIP...",
    downloadStatus: "Status do download",
    downloadDescription: "Resultado da geração compactada do projeto.",
    noDownload: "Nenhum download ainda. Clique em Gerar e baixar para obter o .zip.",
    generateDownloadFailed: "Falha ao gerar e baixar o projeto.",
    invalidDownloadResponse: "Falha ao obter token de download. Resposta inválida do servidor.",
    downloadFileFailed: "Falha ao baixar o arquivo gerado.",
    unexpectedDownloadError: "Falha inesperada no download do zip.",
    cleanupDownloads: "Limpar downloads",
    cleaningDownloads: "Limpando downloads...",
    cleanupDownloadsFailed: "Falha ao limpar os downloads.",
    cleanupDownloadsSuccess: "Downloads limpos com sucesso.",
    nextSteps: "Próximos passos",
    equivalentCli: "CLI equivalente",
    referenceOnly: "Apenas referência. A geração agora acontece direto pelo botão.",
    downloadStarted: "Download iniciado",
    installLine: "instalar",
    runLine: "rodar dev",
    commandPrefix: "pnpm dev:new-project --",
    themes: {
      light: "Claro",
      dark: "Escuro",
      system: "Sistema",
    },
    locales: {
      en: "Inglês",
      pt: "Português",
      es: "Espanhol",
    },
    choices: {
      profile: {
        lite: "Lite",
        full: "Completo",
      },
      language: {
        javascript: "JavaScript",
        typescript: "TypeScript",
      },
      database: {
        json: "JSON",
        postgresql: "PostgreSQL",
        mysql: "MySQL",
        sqlite: "SQLite",
        sqlserver: "SQL Server",
      },
      architecture: {
        layered: "Camadas",
        mvc: "MVC",
        clean: "Clean",
      },
      apiStyle: {
        rest: "REST",
        graphql: "GraphQL",
        hybrid: "Híbrido",
      },
      packageManager: {
        pnpm: "pnpm",
        npm: "npm",
        yarn: "yarn",
        bun: "bun",
      },
      featureSet: {
        auth: "Auth",
        email: "Email",
        both: "Ambos",
        none: "Nenhum",
      },
    },
  },
  es: {
    heroKicker: "StackForge Initializr",
    heroTitle: "Genera y descarga un scaffold de API",
    heroSubtitle: "Elige la pila, el tema y exporta un ZIP con un clic.",
    reset: "Restablecer",
    theme: "Tema",
    locale: "Idioma",
    projectName: "Nombre del proyecto",
    profile: "Perfil",
    language: "Lenguaje",
    database: "Base de datos",
    architecture: "Arquitectura",
    apiStyle: "Estilo de API",
    packageManager: "Gestor de paquetes",
    featureSet: "Conjunto de funciones",
    installSteps: "Mostrar pasos de instalación y ejecución después de generar",
    executeGenerator: "Ejecutar generador",
    generateTitle: "Generar y descargar ZIP",
    generateDescription: "El backend crea el proyecto y devuelve un .zip compacto al navegador.",
    projectWillBeCreated: "Descarga con un clic para",
    projectAdjusted: "Nombre del proyecto ajustado a",
    projectRules: "solo se permiten a-z, 0-9, - y _",
    apiBaseUrl: "URL base de la API",
    usingProxy: "usando proxy /api de Vite",
    generateButton: "Generar y descargar",
    generatingButton: "Generando ZIP...",
    downloadStatus: "Estado de descarga",
    downloadDescription: "Resultado de la generación compacta del proyecto.",
    noDownload: "Todavía no hay descarga. Haz clic en Generar y descargar para obtener el .zip.",
    generateDownloadFailed: "Error al generar y descargar el proyecto.",
    invalidDownloadResponse: "No se pudo obtener el token de descarga. Respuesta inválida del servidor.",
    downloadFileFailed: "No se pudo descargar el archivo generado.",
    unexpectedDownloadError: "Error inesperado al descargar el zip.",
    cleanupDownloads: "Limpiar descargas",
    cleaningDownloads: "Limpiando descargas...",
    cleanupDownloadsFailed: "No se pudieron limpiar las descargas.",
    cleanupDownloadsSuccess: "Descargas limpiadas con éxito.",
    nextSteps: "Siguientes pasos",
    equivalentCli: "CLI equivalente",
    referenceOnly: "Solo referencia. La generación ocurre directamente con el botón.",
    downloadStarted: "Descarga iniciada",
    installLine: "instalar",
    runLine: "ejecutar dev",
    commandPrefix: "pnpm dev:new-project --",
    themes: {
      light: "Claro",
      dark: "Oscuro",
      system: "Sistema",
    },
    locales: {
      en: "Inglés",
      pt: "Portugués",
      es: "Español",
    },
    choices: {
      profile: {
        lite: "Lite",
        full: "Completo",
      },
      language: {
        javascript: "JavaScript",
        typescript: "TypeScript",
      },
      database: {
        json: "JSON",
        postgresql: "PostgreSQL",
        mysql: "MySQL",
        sqlite: "SQLite",
        sqlserver: "SQL Server",
      },
      architecture: {
        layered: "Capas",
        mvc: "MVC",
        clean: "Clean",
      },
      apiStyle: {
        rest: "REST",
        graphql: "GraphQL",
        hybrid: "Híbrido",
      },
      packageManager: {
        pnpm: "pnpm",
        npm: "npm",
        yarn: "yarn",
        bun: "bun",
      },
      featureSet: {
        auth: "Auth",
        email: "Email",
        both: "Ambos",
        none: "Ninguno",
      },
    },
  },
} satisfies InitializrStrings
